# sudo: required

language: bash

services:
  - docker

install:
  - docker-compose build

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - docker-compose run --rm dev

after_script:
  - ./cc-test-reporter after-build -t clover -p /code --exit-code $TRAVIS_TEST_RESULT
